export const metadata = {
  title: 'llamaspit',
  description: 'Generated by Next.js',
}

import '../styles/global.css'
import '@fortawesome/fontawesome-svg-core/styles.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
